apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeservice
  template:
    metadata:
      labels:
        app: kubeservice
    spec:
      containers:
        - name: kubeservice
          image: kubeservice.cmd:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 80