apiVersion: v1
kind: Service
metadata:
  name: kubeservice-service
spec:
  type: NodePort
  selector:
    app: kubeservice
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 32500